# Generated by Django 2.2.12 on 2023-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='hoursWorked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='moneyBalance',
            field=models.IntegerField(default=0),
        ),
    ]
