# Generated by Django 4.1.1 on 2023-04-16 17:16

from django.db import migrations, models

def copy_img(apps, schema_editor):
  Vehicle = apps.get_model('employee', 'Vehicle')
  for vehicle in Vehicle.objects.all():
    vehicle.vehicleImage2 = vehicle.vehicleImage2
    vehicle.save()


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleImage2',
            field=models.ImageField(blank=True, upload_to='vehicles'),
        ),
        migrations.RunPython(copy_img),
    ]
