# Generated by Django 4.1.1 on 2023-04-16 17:19

from django.db import migrations, models

def copy_again(apps, schema_editor):
  Vehicle = apps.get_model('employee', 'Vehicle')
  for vehicle in Vehicle.objects.all():
    vehicle.vehicleImage3 = vehicle.vehicleImage
    vehicle.vehicleImage4 = vehicle.vehicleImage
    vehicle.save()

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_copy_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleImage3',
            field=models.ImageField(blank=True, upload_to='vehicles'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicleImage4',
            field=models.ImageField(blank=True, upload_to='vehicles'),
        ),
        migrations.RunPython(copy_again),
    ]
