# Generated by Django 4.1.1 on 2023-04-16 17:35

from django.db import migrations, models

def copy_again_again(apps, schema_editor):
  Vehicle = apps.get_model('employee', 'Vehicle')
  for vehicle in Vehicle.objects.all():
    vehicle.vehicleImage2 = vehicle.vehicleImage
    vehicle.save()

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_copy_vehicle_image_again'),
    ]

    operations = [
      migrations.RunPython(copy_again_again),
    ]
