# Generated by Django 4.1.2 on 2023-02-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationId', models.IntegerField()),
                ('carId', models.IntegerField()),
                ('userId', models.CharField(max_length=200)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('pickUpAddress', models.CharField(max_length=200)),
                ('needsPickup', models.BooleanField()),
                ('hasInsurance', models.BooleanField()),
                ('isReturned', models.BooleanField()),
            ],
        ),
    ]
