# Generated by Django 4.1.2 on 2023-02-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_pickupaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
