# Generated by Django 4.1.2 on 2023-02-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pickUpAddress',
            field=models.CharField(max_length=300),
        ),
    ]
