# Generated by Django 4.1.2 on 2023-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_pickupaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='carId',
            field=models.UUIDField(editable=False),
        ),
    ]
